### PR TITLE
:sparkles: #1 - Add new editor design for sticky avatar

### PR DESCRIPTION
**Pull request by fpicoitoj**
Added classnames
Worked with tailwind.css in order to achieve tab system for the new layout to allow for sticky avatar to be always on the side (desktop) and on top (mobile)

### CODE REVIEW

**Comment by fpicoitoj** [comment]
Hello @RobertBroersma 

#3  is also taken care of in this PR, but I've only now checked it was mentioned as an issue.

**Comment by RobertBroersma** [comment]
Thanks a lot for this @fpicoitoj 

I noticed in your UI that the avatar is quite large: https://deploy-preview-7--bigheads.netlify.app/editor/

Especially on larger mobile devices I would prefer to see a max width on the character.

Also noticed the code blocks in the Usage tab are overlapping the character. 

Again I really appreciate you taking the time for this, but I'm not entirely sure about this tabbed layout yet.

**Comment by fpicoitoj** [comment]
Hello @RobertBroersma 

Could you tell me:

1. which device you tested on or alternatively the size
2. is there a max-width you have in mind?

Damn, I missed the overlapping due to copy pasta! :)

If there is any other layout you want to try please do tell!

**Comment by RobertBroersma** [comment]
@fpicoitoj I've tested on 1920 width desktop and some mobile format. Mobile is where the problem occurs :)

The thing is I want to add some more documentation for the REST API for SVG images, as this is one of the main uses of the app. This is why I want to change the layout to something more documentation-like.

**Comment by fpicoitoj** [comment]
Hello again @RobertBroersma !

Should I fix the bug, and apply a max-width as per your indication, and change more stuff (a small tweak to the UI perhaps?) or do you want to tackle that UI part on your own?

By the way you tagged the wrong user!

**Comment by RobertBroersma** [comment]
@fpicoitoj Whoops! You are right. I updated the comment.

I'm a very picky person, and I would hate to disappoint you/waste your time, so I think I'm gonna figure this one out by myself, sorry!

I still much appreciate you took the time to open a PR tho, thanks again!

**Comment by fpicoitoj** [comment]
Sure, good luck!

**Pull request closed without merging**
